version: '2.2'

services:
  bechmark_ids_php:
    build:
      context: ./
      dockerfile: Dockerfile
    user: ${DOCKER_USER_ID}
    environment:
      DATE_TIMEZONE: "Europe/Amsterdam"
      ###> Xdebug ###
      PHP_IDE_CONFIG: "serverName=${PROJECT}" # This is needed to debug from CLI (ie. while running tests)
      XDEBUG_CONFIG: cli_color=1 client_host=${HOST_IP} xdebug.client_port=9003 discover_client_host=false idekey=PHPSTORM log=/var/www/var/xdebug.log log_level=7 mode=develop,debug output_dir=/var/www/var/xdebug profiler_output_name=cachegrind.out.%p
      ###< Xdebug ###
    volumes:
      - ../:/var/www # so we can easily change the application code running in the container
      - ~/.composer:/.composer # so we can use the host composer cache
      - ./php.ini:/usr/local/etc/php/php.ini # so we can easily change php config
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # so we can easily change xdebug config
      - ../var/mysql-files:/var/lib/mysql-files/ # So that we can create tests that create files with mysql and are deleted by php

  bechmark_ids_mysql:
    image: mysql:5.7
#    mem_limit: 512M
#    mem_reservation: 256M
#    cpus: 1
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: benchmark
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Amsterdam
    volumes:
      - ../var/mysql:/var/lib/mysql # so that we don't lose our dev/test DBs when we destroy the container
      - ../var/mysql-files:/var/lib/mysql-files/
    command: ['mysqld', '--sql_mode=STRICT_TRANS_TABLES', '--default-time-zone=+02:00', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

networks:
  default:
    external: # This way the network is always the same, predictable, so we can get the IP it is using, and docker won't create a new adapter each time we run it.
      name: ${DOCKER_NETWORK}
